name = "lado"
description = "Logic Analyzer/Digital Oscilloscope"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded"]

project-files = ["gnat/lado.gpr"]

[configuration]
#disabled = true

[[depends-on]]
a0b_armv7m_systick_clock_timer = "*"
a0b_stm32h723 = "*"
a0b_stm32h723_gpio = "*"
light_fk723m1_zgt6 = "*"

[[pins]]
a0b_armv7m = { path='../a0b-armv7m' }
a0b_base = { path='../a0b-base' }
a0b_callbacks = { path='../a0b-callbacks' }
a0b_exti = { path='../a0b-exti' }
a0b_gpio = { path='../a0b-gpio' }
a0b_stm32h723 = { path='../a0b-stm32h723' }
a0b_stm32h723_gpio = { path='../a0b-stm32h723-gpio' }
a0b_tasking = { path='../a0b-tasking' }
a0b_time = { path='../a0b-time' }
a0b_timer = { path='../a0b-timer' }
